# ======================================================================
# ctapipe-ml-train-particle-classifier config file.
# version: 0.16.1.dev193+g1c55d1e6
#
# Configuration for training machine-learning models
# ======================================================================
TrainParticleClassifier:
  CrossValidator:
    n_cross_validations: 5

  ParticleClassifier:
    model_cls: RandomForestClassifier
    model_config:
      n_estimators: 200
      min_samples_leaf: 100
      n_jobs: -1

    features:
      - hillas_intensity
      - hillas_r
      - hillas_length
      - hillas_width
      - hillas_skewness
      - hillas_kurtosis
      - timing_slope
      - timing_deviation
      - leakage_intensity_width_1
      - leakage_intensity_width_2
      - leakage_pixels_width_1
      - leakage_pixels_width_2
      - concentration_cog
      - concentration_core
      - morphology_n_islands
      - morphology_n_large_islands
      - morphology_n_medium_islands
      - morphology_n_pixels
      - morphology_n_small_islands
      - HillasReconstructor_tel_impact_distance
      - HillasReconstructor_average_intensity
      - HillasReconstructor_h_max
      - peak_time_std
      - peak_time_skewness
      - peak_time_kurtosis
      - intensity_max
      - intensity_mean
      - intensity_std
      - intensity_skewness
      - intensity_kurtosis
      - area
      - RandomForestRegressor_energy     # mean energy of the array event
      - RandomForestRegressor_tel_energy # mono prediction

    QualityQuery:
      quality_criteria:
        - ["HillasValid", "HillasReconstructor_is_valid"]
        - ["enough intensity", "hillas_intensity > 50"]
        - ["Positive width", "hillas_width > 0"]
        - ["enough pixels", "morphology_n_pixels > 3"]
        - ["not clipped", "leakage_intensity_width_2 < 0.5"]

    FeatureGenerator:
      features:
        - ["area", "hillas_width * hillas_length"]
